### PR TITLE
Create hello_world_melvincwng.js

### PR DESCRIPTION
**Pull request by melvincwng**
Add hello world script in Chinese

### CODE REVIEW

**Comment by melvincwng** [comment]
@calixtocarolina Hi Carolina, for your kind review & approval :)

Please kindly assign this PR to me & also add the labels 'hacktoberfest' & 'hacktoberfest-accepted' if PR is approved.

Happy Hacktoberfest 2022, and cheers 🎉

**Review by calixtocarolina — APPROVED** [review]

**Comment by calixtocarolina** [comment]
Thanks for contributing!

**Comment by melvincwng** [comment]
@calixtocarolina Hi Carolina, the PR is not merged?

**Comment by melvincwng** [comment]
@calixtocarolina , I think you may have accidentally closed all the PRs without merging.

Please reopen the closed PRs, and approve again, and merge them - for HacktobeFest contribution.

Thanks!

**Pull request merged**
