### PR TITLE
Added hello world in marathi

### PR DESCRIPTION
**Pull request by mh31-priyanshu**

### CODE REVIEW

**Comment by mh31-priyanshu** [comment]
@calixtocarolina hey i've sent a pull request please do check out

**Comment by calixtocarolina** [comment]
Thanks for contributing, greetings from Brazil!

**Comment by mezotv** [comment]
@calixtocarolina I think you might accidentally closed this instead of merging

**Comment by mh31-priyanshu** [comment]
> @calixtocarolina I think you might accidentally closed this instead of merging

@calixtocarolina i'm also wondering the same thing 😅

**Comment by mh31-priyanshu** [comment]
Hey @mezotv does the owner of repo still get notified of my comment after closing PR?

**Comment by mezotv** [comment]
> Hey @mezotv does the owner of repo still get notified of my comment after closing PR?

They should since I mentioned them.

**Pull request merged**
